name = "mmsppg-docs"
compatibility_date = "2025-10-03"

# This tells wrangler we're deploying to Pages, not Workers
pages_build_output_dir = "dist"

# Environment variables should be set in Cloudflare dashboard
# DIRECTUS_URL
# DIRECTUS_TOKEN